### ISSUE TITLE
Typo in Medium article

### ISSUE THREAD

**Issue by slarionoff** [Alexkuva/The-Rougon-Macquart-project#4]
Hi there! 
This is about an [article](https://medium.com/datalex/computing-total-storage-size-of-a-folder-in-azure-data-lake-with-pyspark-b6ef649f9eca). In a section "Define functions" you have the same description "Calculate number of Files and number of Folders for a specific path" for both functions. 1st one should be about the size, I guess.

**Comment by Alexkuva** [comment]
Thank you for your feedback, I just edit the article :)

**Comment by Alexkuva** [comment]
Did u install this library : azure.datalake.store ?
